[env:remote_box]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps =
  olikraus/U8g2@^2.35.30
  bblanchon/ArduinoJson@^6.21.5
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
